import type { ToolDefinition } from "@/lib/tools/types";
import type { RoasInput } from "@/lib/tools/engines/roas-calculator";

export const roasContent: ToolDefinition<RoasInput> = {
  slug: "roas-calculator",
  h1: "ROAS Calculator",
  intro:
    "Return on ad spend is the revenue a campaign produced for every unit of currency you put into it. Enter what you spent and what it brought back, and this works out the ratio, the same figure as a percentage, and how much revenue is left once the ad bill is paid.",

  formula: {
    expression: "ROAS = Revenue from ads ÷ Ad spend",
    explanation:
      "Divide the revenue a campaign generated by what it cost to run. A ROAS of 4 means every 1 you spent returned 4 in revenue. Multiplying by 100 expresses the same thing as a percentage, which is how some ad platforms report it.",
  },

  example: {
    inputs: { revenue: 8000, adSpend: 2000 },
    narrative:
      "A campaign spends 2,000 and is credited with 8,000 in revenue. 8,000 ÷ 2,000 = 4.00×, or 400%. That leaves 6,000 of revenue after the ad bill — but not 6,000 of profit, because the cost of the goods sold has not been taken out yet.",
  },

  interpretation: [
    "ROAS above 1.00× means the campaign returned more revenue than it cost in ad spend. It does not mean the campaign made money.",
    "Whether a given ROAS is profitable depends entirely on your gross margin. At a 40% margin you need 2.50× just to break even, so 2.00× is a loss even though it looks like a gain.",
    "Compare ROAS only across campaigns with similar attribution settings and windows. A 7-day-click campaign and a 28-day-click campaign are not measuring the same thing.",
    "A very high ROAS on a small spend often means the campaign is under-funded rather than brilliant. It can be worth accepting a lower ROAS at a higher spend if total profit rises.",
  ],

  commonMistakes: [
    "Treating ROAS as profit. It compares revenue to ad spend only — cost of goods, shipping, payment fees and overheads are all still to come.",
    "Comparing your ROAS to a number someone quoted online. A 'good' ROAS is set by your margin, not by an industry benchmark.",
    "Using total store revenue instead of revenue attributed to the campaign, which flatters the figure with sales the ads had nothing to do with.",
    "Mixing periods — this month's revenue against last month's spend — which is especially misleading for products with a long consideration window.",
  ],

  faqs: [
    {
      q: "What is a good ROAS?",
      a: "There is no universal answer, because the break-even point is set by your gross margin. Divide 1 by your margin as a decimal: at a 40% margin, break-even is 1 ÷ 0.40 = 2.50×, so anything above that contributes profit. At a 20% margin you need 5.00× for the same outcome. Use the Break-Even ROAS Calculator to find yours.",
    },
    {
      q: "Is ROAS the same as ROI?",
      a: "No. ROAS compares revenue to ad spend. ROI compares profit to total investment. A campaign can have a strong ROAS and a negative ROI if the margin on what it sold is thin.",
    },
    {
      q: "Should I use revenue before or after returns?",
      a: "After returns and discounts, if you can. Using gross revenue overstates ROAS for any store with a meaningful return rate, and the gap widens in categories like apparel where returns are common.",
    },
    {
      q: "Why does my ad platform report a different ROAS than my store?",
      a: "Ad platforms attribute conversions using their own click and view windows, and they count a sale against the campaign that touched it. Your store counts the order once. The platform figure is usually the higher of the two, and the difference is not an error in either system.",
    },
  ],

  relatedTools: ["break-even-roas-calculator", "cpc-calculator", "ecommerce-profit-calculator"],
  relatedGuides: [],

  seo: {
    title: "ROAS Calculator — Work Out Return on Ad Spend",
    description:
      "Free ROAS calculator. Enter ad spend and attributed revenue to get return on ad spend as a ratio and a percentage, with the formula and a worked example.",
  },
};
